print('                          leeme                           ')
print('------------------------------------------------------------')
print('|                    Descubro tu edad                      |')
print('|               Introduce lo que se te pida                |')
print('| Cuando ponga Y/N pon una Y si estas de acuerdo y N si no |')
print('|      Todos los parametros son con el sistema metrico     |')
print('|        En la estatura se utilizara el formato 1.xx       |')
print('------------------------------------------------------------')
nombre = input('Introduce tu nombre: ')
print('Introduce tu sexo')
sexo = input('M/H:')
estatura = input('Introduce tu estatura: ')
Escuela = input('Cual es tu grado maximo de estudios: ')
